### ISSUE TITLE
Problems with the participle function

### ISSUE THREAD

**Issue by stardust-xc** [plandes/mednlp#1]
I'm getting the following error when I use mednlp to process my text into words, is there any way to fix it?
Traceback (most recent call last):
  File "slipwords.py", line 1, in <module>
    from zensols.mednlp import ApplicationFactory
  File "/root/miniconda3/lib/python3.8/site-packages/zensols/mednlp/__init__.py", line 7, in <module>
    from .app import *
  File "/root/miniconda3/lib/python3.8/site-packages/zensols/mednlp/app.py", line 17, in <module>
    from zensols.cli import ApplicationError
  File "/root/miniconda3/lib/python3.8/site-packages/zensols/cli/__init__.py", line 17, in <module>
    from .lib.support import *
  File "/root/miniconda3/lib/python3.8/site-packages/zensols/cli/lib/support.py", line 392, in <module>
    class Cleaner(DryRunApplication):
  File "/root/miniconda3/lib/python3.8/site-packages/zensols/cli/lib/support.py", line 399, in Cleaner
    CLI_META = ActionCliManager.combine_meta(
  File "/root/miniconda3/lib/python3.8/site-packages/zensols/cli/action.py", line 396, in combine_meta
    self._combine_meta(meta, cli_meta)
  File "/root/miniconda3/lib/python3.8/site-packages/zensols/cli/action.py", line 370, in _combine_meta
    target[attr] = targ_val | src_val
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

**Comment by plandes** [comment]
Hi @stardust-xc,

It looks like you have a version of Python lower than 3.9.  Can you please confirm this (i.e. `python --version`)?
